<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_role('id_admin', '1', '../admin-login.php');
$pdo = app_pdo(); $theme = current_theme();
$cliente = fetch_one($pdo->prepare('SELECT * FROM clientes WHERE id_cliente = :id'), array(':id' => request_query_int('id_cliente')));
if ($cliente === null) { app_redirect('../admin-dashboard.php#clientes', 'Cliente no encontrado'); }
?>
<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Editar cliente</title><script src="https://cdn.tailwindcss.com"></script><style>:root{--primary:<?php echo escape_html($theme['primary']); ?>;--secondary:<?php echo escape_html($theme['secondary']); ?>;}body{background:linear-gradient(180deg,#f8fafc 0%,#edf2f7 100%);}</style></head><body class="min-h-screen px-4 py-8 text-slate-900 sm:px-6"><main class="mx-auto max-w-4xl rounded-[2rem] border border-white/50 bg-white/85 p-6 shadow-2xl backdrop-blur-xl sm:p-8"><a class="text-sm font-medium text-slate-500 hover:text-slate-900" href="../admin-dashboard.php#clientes">← Volver</a><h1 class="mt-4 text-3xl font-semibold">Editar cliente</h1><form action="update.php?id_cliente=<?php echo escape_html((string) $cliente['id_cliente']); ?>&accion=cliente" method="post" class="mt-6 grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium text-slate-600">Nombre<input class="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" name="nombre_cliente" value="<?php echo escape_html($cliente['nombre_cliente']); ?>" required></label><label class="block text-sm font-medium text-slate-600">Apellido<input class="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" name="apellido_cliente" value="<?php echo escape_html($cliente['apellido_cliente']); ?>" required></label><label class="block text-sm font-medium text-slate-600">Telefono<input class="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" name="telefono_cliente" value="<?php echo escape_html($cliente['telefono_cliente']); ?>" required></label><label class="block text-sm font-medium text-slate-600">Correo<input class="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" name="correo_cliente" type="email" value="<?php echo escape_html($cliente['correo_cliente']); ?>" required></label><label class="block text-sm font-medium text-slate-600">Usuario<input class="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" name="user_cliente" value="<?php echo escape_html($cliente['user_cliente']); ?>" required></label><label class="block text-sm font-medium text-slate-600">Nueva contraseña<input class="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" name="pass_cliente" type="password" minlength="8"></label><label class="block text-sm font-medium text-slate-600 sm:col-span-2">Notas<input class="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" name="notas_cliente" value="<?php echo escape_html($cliente['notas_cliente']); ?>"></label><button class="sm:col-span-2 inline-flex items-center justify-center rounded-2xl px-6 py-3 text-sm font-semibold text-white shadow-lg" style="background:linear-gradient(135deg,var(--secondary),var(--primary));" type="submit">Guardar cambios</button></form></main></body></html>
